person:
#  生成随机数
  name: qinjiang${random.uuid}
  age: 110
  happy: false
  birth: 2020/07/13
  email: hohowrongemail@mail.com
  maps: {k1: v1,k2: v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: ${person.hell:hello}_旺财
    age: 3